### ISSUE TITLE
多行文本超出div高度，需要让在div内得最后一行结尾用...表示

### ISSUE THREAD

**Issue by lizhongzhen11** [lizhongzhen11/dailyGain#46]
一提到用...表示，其实有点经验得都会想到下面的css
```css
.curt {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

但是，这种方法只能对单行文本有用，如果是多行的话，它会把每行都给用...表示，很明显不满足需求。

网上倒是有几个方法，记录下：
1. 数div内能正常展示的字数，然后substring()截取，最后+'...'；虽然low，不过确实能完成任务
2. 纯css
    ```css
    div {
      display: -webkit-box;
      overflow : hidden;
      text-overflow: ellipsis;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
    }
    ```

第二种方法缺点也明显，看前缀就知道只能在webkit内核的浏览器中生效。
